;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname 5.1_5.2) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f () #f)))
; ------------------------------------------------
(display "  UENF-CCT-LCMAT-CC, 2021")
(newline)
(display "  Paradigmas de Linguagens de Programação (Prof. Ausberto Castro)")
(newline)
(display "  Aluno: Eduardo Ferreira")
(newline)
(display "---------------------------------------------------")
(newline)
(display "x = 3")
(newline)
(define x 3)
(display "m = 7")
(newline)
(define m 7)
(display "z = m + 6")
(newline)
(define z (+ m 6))
(display "Pi = 3.141516")
(newline)
(define Pi 3.141516)
(display "k = z + (m - x)")
(newline)
(define k (+ z (- m x)))
(display "quadrao x = x^2")
(newline)
(define (quadrado x)            
    (* x x)  )

(display "entre5e20? n: 5<n<20 = true, 5>n = false, n>20")
(newline)
(define (entre5e20? n)
  (and (< 5 n) (< n 20) )              
 )
(display "---------------------------------------------------")

(newline)
(display "O numero 8 esta entre 5 e 20? ")
(entre5e20? 8)

(newline)
(display "O numero 37 esta entre 5 e 20? ")
(entre5e20? 37)

(newline)
(display "Escreva qualquer variavel definida acima ... <var> <ENTER>   x m z Pi")
(newline)
(display "---------------------------------------------------")
(newline)
(display "Exercicio 5.1")
(newline)
(newline)
(display "A nova declaração da variavel esta associada apenas a opereções dentro do oscopo de let, assim fazendo que após a operação dada ela volte ao seu valor original.")
(newline)
(let ((x 24)) 
  (+ x 6))   

(newline)
(display "Uma opreção com o mesmo argumento sobre let da anterior que tambem mostra a procedencia em que as operações são realizadas.")
(newline)
(let ( (a 5) (b 8)) 
  (+ 3 (* a b)))    

(newline)
(display "Mostra que em racket pode ser associar simbolos de operação facilmente e chamalos como se fosse objetos")
(newline)
(let ( (op1 +) 
       (op2 *) 
       (x 5)
         )      
   
  (op1 3 (op2 4 x)) 
)

(display "O quadrado de 12 : ")(quadrado 12)

(display "Exercicio 5.2")
(newline)
(newline)

(display "i)")
(newline)
(display "Se comparando aos valores dados as variaveis anteriomente vai ver mudança criada por let ")
(newline)
(let ((x 4) (y 3))
  (* x y))


(newline)
(display "ii)")
(newline)
(display "Exemplificando bem que após sairem da função eles retornam ao valor original, fazendo a mesma operação se obtem valores distitos")
(newline)
(display "Em let:")
(let ((x 3) (m 5))
  (+ x m))
(display "Fora do let:")
(display (+ m x))