;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname |6.1|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f () #f)))
(display "  UENF-CCT-LCMAT-CC, 2021")
(newline)
(display "  Paradigmas de Linguagens de Programação (Prof. Ausberto Castro)")
(newline)
(display "  Aluno: Eduardo Ferreira")
(newline)
(newline)
(display "---------------------------------------------------")
(newline)
(display "Exercicio 6")
(newline)
(newline)
(display "Definindo a função e seus parametros")
(newline)
(display "(define (area-circulo r) 
  (* 3.14 (* r r))         )")
(newline)
(define (area-circulo r) 
  (* 3.14 (* r r))         )
(newline)
(display "Definindo a função e seus parametros")
(newline)
(display "(define (areatriangulo b h)
  (/ (* b h) 2))
")
(newline)
(define (areatriangulo b h)
  (/ (* b h) 2))
(newline)
(display "Definindo a função e seus parametros")
(newline)
(display "(define (areadisco interno externo)
  (- (area-circulo externo)
     (area-circulo interno)
  )
)")
(newline)
(define (areadisco interno externo)
  (- (area-circulo externo)
     (area-circulo interno)
  )
)
(newline)
(display "(area-circulo 18) = Chamando a função e agregando valores ao seus parametros")
(newline)
(display "Circulo de raio 18   AREA = ")
(area-circulo 18)
(newline)
(display "(areatriangulo 10 15) = Chamando a função e agregando valores ao seus parametros")
(newline)
(display "Triangulo base=10, altura=15  AREA =   ")
(areatriangulo 10 15)
(newline)
(display "(areadisco 12 20) = Chamando a função e agregando valores ao seus parametros")
(newline)
(display "Disco raio menor=12, raio maior=20  AREA = ")
(areadisco 12 20)
(newline)
(display "---------------------------------------------------")
(newline)
(display "Exercicio 6.1")
(newline)
(newline)
(define (area_quadrado b h)
  (* b h)
)

(define (area_trapezio B b h)
  (/ (* (+ B b) h) 2)
)

(define (area_poligono p a)
  (/ (* p a) 2)
)

(display "Quadrado de base(b) = 2, altura(h) = 2; área = ")
(area_quadrado 2 2)
(newline)
(display "Trapézio base maior(B) = 8, base menor(b) = 5, altura(h) = 6; área = ")
(area_trapezio 8 5 6)
(newline)
(display "Polígono de lado(p) = 2, apótema(a) = 4; área = ")
(area_poligono 5 3)
(newline)
(display "---------------------------------------------------")

