(display "  UENF-CCT-LCMAT-CC, 2021")
(newline)
(display "  Paradigmas de Linguagens de Programação (Prof. Ausberto Castro)")
(newline)
(display "  Aluno:  Eduardo Ferreira ")
(newline)
(display "---------------------------------------------------")
(newline)
(display "Exercicio 7.2")
(newline)
(display "i)")
(define Multiplicação
        (lambda (x y)
          (begin
            (newline)
            (display x)
            (display " x ")
            (display y)
            (display " = ")
            (* x y)
            )
          )
  )

(Multiplicação 4 2)
(newline)
(display "ii)")
(define Cubico
     (lambda ( x )
       (newline)
       (display x)
       (display " ao cubo é ")
       (* ( * x x) x)
       )
  )
(Cubico 2)