(display "  Paradigmas de Linguagens de Programação (Prof. Ausberto Castro)")
(newline)
(display "  Aluno:  Eduardo Ferreira ")
(newline)
(display "---------------------------------------------------")
(newline)
(display "Exercicio 8.1")
(newline)
(display "i)")

(define (media p1 p2)
  (/(+ p1 p2) 2)
  )

(define (media_final p1 p2 pf)
 (/ (+(+ p1 p2) pf) 3)
  )

(define (recuperação p1 p2 p3)
  (if (<= 5 (/ (+ (+ p1 p2) p3) 3))
         (display "aprovado")
         (display "reprovado")
         )
)
  
(define (escola_notas p1 p2)
  (if (<= 6 (/ (+ p1 p2) 2))
      (display "aprovado")
      (display "recuperação, após a p3 tentar novamente.")
  )
)
(newline)
(display "Notas: p1 = 5, p2 = 5 situação: ")
(escola_notas 5 5)
(newline)
(display "Sua media foi de ")
(media 5 5)
(newline)
(display "Notas: p1 = 5, p2 = 5, p3 = 5 situação: ")
(recuperação 5 5 5)
(newline)
(display "Sua media final foi de ")
(media_final 5 5 5)
(newline)
(display "---------------------------------------------------")
(newline)
(display "Exercicio 8.2")
(define (maior n1 n2)
  (if (> n1 n2)
      (display n1)
      (display n2)
  )
)

(newline)

(display "O maior número é ")
(maior 10 5)